DEFAULTS = {
    "continuous": {
        "ga": {
            "population_size": 50,
            "generations": 100,
            "crossover_rate": 0.8,
            "mutation_rate": 0.1,
            "tournament_size": 3,
            "blx_alpha": 0.5,
        },
        "pso": {
            "num_particles": 30,
            "iterations": 100,
            "w": 0.7,
            "c1": 1.5,
            "c2": 1.5,
            "vmax": 5.0,
        },
        "aco": {
            "num_ants": 10,
            "iterations": 100,
            "k": 10,
            "q": 0.01,
            "xi": 0.85,
        },
        "ais": {
            "population_size": 30,
            "generations": 100,
            "beta": 1.0,
            "d": 0.1,
            "rho": 3.0,
        },
        "de": {
            "population_size": 50,
            "generations": 100,
            "F": 0.8,
            "CR": 0.9,
            "strategy": "DE/rand/1",
        },
    },
    "knapsack": {
        "ga": {
            "population_size": 50,
            "generations": 100,
            "crossover_rate": 0.8,
            "mutation_rate": 0.1,
            "tournament_size": 3,
        },
        "pso": {
            "num_particles": 30,
            "iterations": 100,
            "w": 0.7,
            "c1": 1.5,
            "c2": 1.5,
            "vmax": 5.0,
        },
        "aco": {
            "num_ants": 20,
            "iterations": 100,
            "alpha": 1.0,
            "beta": 2.0,
            "rho": 0.1,
            "Q": 100.0,
            "tau0": 0.1,
        },
        "ais": {
            "population_size": 30,
            "generations": 100,
            "beta": 1.0,
            "d": 0.1,
            "rho": 3.0,
        },
        "de": {
            "population_size": 50,
            "generations": 100,
            "F": 0.8,
            "CR": 0.9,
            "strategy": "DE/rand/1",
        },
    },
    "categorical": {
        "ga": {
            "population_size": 50,
            "generations": 100,
            "crossover_rate": 0.8,
            "mutation_rate": 0.1,
            "tournament_size": 3,
            "blx_alpha": 0.5,
        },
        "pso": {
            "num_particles": 30,
            "iterations": 100,
            "w": 0.7,
            "c1": 1.5,
            "c2": 1.5,
            "vmax": 5.0,
        },
        "aco": {
            "num_ants": 10,
            "iterations": 100,
            "k": 10,
            "q": 0.01,
            "xi": 0.85,
        },
        "ais": {
            "population_size": 30,
            "generations": 100,
            "beta": 1.0,
            "d": 0.1,
            "rho": 3.0,
        },
        "de": {
            "population_size": 50,
            "generations": 100,
            "F": 0.8,
            "CR": 0.9,
            "strategy": "DE/rand/1",
        },
    },
    "tsp": {
        "ga": {
            "population_size": 50,
            "generations": 200,
            "crossover_rate": 0.9,
            "mutation_rate": 0.05,
            "tournament_size": 3,
        },
        "pso": {
            "num_particles": 30,
            "iterations": 200,
            "w": 0.7,
            "c1": 0.7,
            "c2": 0.7,
        },
        "aco": {
            "num_ants": 20,
            "iterations": 200,
            "alpha": 1.0,
            "beta": 5.0,
            "rho": 0.1,
            "Q": 100.0,
            "tau0": 0.1,
        },
        "ais": {
            "population_size": 30,
            "generations": 200,
            "beta": 1.0,
            "d": 0.1,
            "rho": 3.0,
        },
        "de": {
            "population_size": 50,
            "generations": 200,
            "F": 0.8,
            "CR": 0.9,
            "strategy": "DE/rand/1",
        },
    },
}
